# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wf_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='wf_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
